pipeline {
    agent any

    environment {
        AWS_REGION = 'us-east-1'
        TF_IN_AUTOMATION = 'true'
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/satyavi0101/docker-demo-with-simple-python-app.git'
            }
        }

        stage('Terraform Init & Apply') {
            steps {
                sh '''
                    echo "🔧 Initializing Terraform"
                    terraform --version
                    terraform init
                    terraform apply -auto-approve
                '''
            }
        }

        stage('Output Deployment Info') {
            steps {
                sh '''
                    echo "📦 Deployment Output:"
                    terraform output
                '''
            }
        }
    }

    post {
        success {
            echo '✅ Terraform provisioning completed successfully.'
        }
        failure {
            echo '❌ Terraform provisioning failed. Check the logs.'
        }
    }
}
